# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  dbcli:
    build:
      context: ../..
      dockerfile: ./build/Dockerfile.seed
    networks:
      - shared-network
    command: >
      bash -c "./dbcli migrate
      && ./dbcli seed"
    environment:
      - DEPOSITS_DB_DISABLE_TLS=true