# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  deposits_shared_network:
    driver: bridge

services:

  curlcli:
    image: curlimages/curl
    volumes:
      - "$PWD/config/tls:/tlscurl"
    networks:
      - deposits_shared_network
    command: "--cacert tlscurl/cacert.crt --request POST 'https://interestsvcserver:3000/v1/health' --header 'Content-Type: application/json'"