# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

networks:
  deposits_shared_rest_network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: deposits_db
    networks:
      - deposits_shared_rest_network
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - deposits_shared_rest_network
    image: openzipkin/zipkin:2.11
    ports:
      - 9411:9411