apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-deposits
  labels:
    app: postgres
data:
  DEPOSITS_DB_USER: "postgres"
  DEPOSITS_DB_PASSWORD: "postgres"
  DEPOSITS_DB_HOST: "db"
  DEPOSITS_DB_NAME: "postgres"
  DEPOSITS_DB_DISABLE_TLS: "true"