apiVersion: batch/v1
kind: Job
metadata:
  name: seed
spec:
  template:
    metadata:
      name: seed
    spec:
      containers:
        - name: seed
          image: rsachdeva/illuminatingdeposits.seed:v1.3.0
          command:
            - "bash"
            - "-c"
            - "./dbcli migrate && ./dbcli seed"
          envFrom:
            - configMapRef:
                name: postgres-config-deposits
      restartPolicy: Never
